### PR TITLE
Fix issue with workflow not working on `master` branch.

### PR DESCRIPTION
**Pull request by deepjyoti30**
@riteshkgupta395 You workflow was set to run on push to the `master` branch. However, your working branch is `main`. Thus the workflow file wasn't working whenever you pushed to that branch.

This PR should fix the issue!

### CODE REVIEW

**Comment by riteshkgupta395** [comment]
fixed

**Comment by riteshkgupta395** [comment]
@deepjyoti30 i tried but getting below error,pls help.

1s
Run joonvena/robotframework-docker-action@v0.1
/usr/bin/docker run --name ppodgorsekrobotframeworklatest_962675 --label 3bec5f --workdir /github/workspace --rm -e BROWSER -e ROBOT_TESTS_DIR -e ROBOT_REPORTS_DIR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Robotframework/Robotframework":"/github/workspace" ppodgorsek/robot-framework:latest
mkdir: cannot create directory ‘/github/workspace/reports’: Permission denied
[ ERROR ] Parsing '/github/workspace/robot_tests' failed: File or directory to execute does not exist.

Try --help for usage information.
0s
Run actions/upload-artifact@v1
Error: Path does not exist /home/runner/work/Robotframework/Robotframework/reports
Error: Exit code 1 returned from process: file name '/home/runner/runners/2.279.0/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.


in git action job can u pls help me

**Comment by deepjyoti30** [comment]
@riteshkgupta395 It's saying that the `robot_tests` directory is not present.

You are probably passing something wrong regarding that directory!

**Comment by deepjyoti30** [comment]
@riteshkgupta395 Regarding the first error, the robot framework is not able to create the directory automatically, ideally you'd have to run it with `sudo` but I don't know how to use sudo with a github action itself so you can try creating the directory before the framework step runs, this way they won't try to create the directory.

Add the following steps before the `testcase` step:

```yaml
- name: Create directory
  run: sudo mkdir ${{ github.workspace }}/robot_tests
- name: Create reports directory
  run: sudo mkdir ${{ github.workspace }}/reports
```

**Comment by riteshkgupta395** [comment]
> @riteshkgupta395 Regarding the first error, the robot framework is not able to create the directory automatically, ideally you'd have to run it with `sudo` but I don't know how to use sudo with a github action itself so you can try creating the directory before the framework step runs, this way they won't try to create the directory.
> 
> Add the following steps before the `testcase` step:
> 
> ```yaml
> - name: Create directory
>   run: sudo mkdir ${{ github.workspace }}/robot_tests
> - name: Create reports directory
>   run: sudo mkdir ${{ github.workspace }}/reports
> ```

unable to undertsand where i should put in the  file can u pls help me

**Comment by deepjyoti30** [comment]
@riteshkgupta395 You need to insert those lines after line `11` in the `action.yml` file.

Make sure you properly indent the file after pasting the content!

**Comment by riteshkgupta395** [comment]
@deepjyoti30 thanks i tried but again new error 
Warning: Unexpected input(s) 'name', 'path', valid inputs are ['entryPoint', 'args']
Run joonvena/robotframework-docker-action@v0.1
  with:
    name: reports
    path: /home/runner/work/Robotframework/Robotframework/reports
  env:
    BROWSER: chrome
    name: Upload test results
    uses: actions/upload-artifact@v1
/usr/bin/docker run --name ppodgorsekrobotframeworklatest_33082d --label 3bec5f --workdir /github/workspace --rm -e BROWSER -e name -e uses -e INPUT_NAME -e INPUT_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Robotframework/Robotframework":"/github/workspace" ppodgorsek/robot-framework:latest
[ ERROR ] Parsing '/opt/robotframework/tests' failed: File or directory to execute does not exist.

Try --help for usage information.

**Comment by deepjyoti30** [comment]
@riteshkgupta395 This means the values you're passing to the RobotFramework action are not valid.

From your config I can see that you're passing the values: `name` and `uses`are not properly intended. They should be at the same level as the `name` value in the lines above.

**Pull request closed without merging**
